Vgather/Models/Service.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vgather.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class Service
    {
        [Required(ErrorMessage = "Please Enter your company Name")]
        [DataType(DataType.Text)]
        [RegularExpression("^[a-zA-Z ]{3,20}$", ErrorMessage = "Invalid Company Name")]
        [Display(Name = "Company Name")]
        public string Company_Name { get; set; }

        [Required(ErrorMessage = "Please Enter Description")]
        [DataType(DataType.Text)]
        [RegularExpression("^[a-zA-Z ]{3,20}$", ErrorMessage = "Invalid Description")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please Enter Type")]
        [DataType(DataType.Text)]
        [RegularExpression("^[a-zA-Z ]{3,20}$", ErrorMessage = "Invalid Type")]
        [Display(Name = "Type")]
        public string Type { get; set; }

        [Required(ErrorMessage = "Please Enter your EmailId")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        [Display(Name = "Email ID")]
        public string Contact_Email { get; set; }

        [Required(ErrorMessage = "Please Enter your Address")]
        [DataType(DataType.Text)]
        [RegularExpression("^[a-zA-Z ]{3,20}$", ErrorMessage = "Invalid Address")]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Display(Name = "Phone Number")]
        [RegularExpression("^[789][0-9]{9}$", ErrorMessage = "Enter Valid Mobile Number")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Please Enter Valid Phone Number")]
        public string Phone_no { get; set; }

        [ValidateFile(ErrorMessage = "Please select a PNG image smaller than 1MB")]
        [Display(Name = "Certification")]
        public string Certification { get; set; }

        [Required(ErrorMessage = "Please Enter your serviceID ")]
        [DataType(DataType.Text)]
        [RegularExpression("^[a-zA-Z ]{3,20}$", ErrorMessage = "Invalid serviceID")]
        [Display(Name = "Service ID")]
        public int serviceID { get; set; }
    }
}

Vgather/Models/serviceType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vgather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public serviceType()
        {
            this.EventBookings = new HashSet<EventBooking>();
            this.service_company = new HashSet<service_company>();
        }
    
        public string ServiceTypeID { get; set; }
        public string ServiceType1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventBooking> EventBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_company> service_company { get; set; }
    }
}

Vgather/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vgather.Models;

namespace ServicesController.Controllers
{
    public class ServicesController : Controller
    {

        EventManagementEntities1 db = new EventManagementEntities1();

        // GET: Services
        public ActionResult Index()
        {
            return View(db.Services.ToList());
        }

        // GET: Services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Company_Name,Description,Type,Contact_Email,Address,Phone_no,Certification,serviceID")] Service service)
        {
            if (ModelState.IsValid)
            {
                db.Services.Add(service);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(service);
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Add(Service s,
            HttpPostedFileBase ImageUpload)
        {
            if (ModelState.IsValid)
            {
                string myfilename = Path.GetFileNameWithoutExtension(ImageUpload.FileName);

                string extension = Path.GetExtension(ImageUpload.FileName);

                myfilename = myfilename + extension;
                s.Certification = "~/Images/" + myfilename;
                myfilename = Path.Combine(Server.MapPath("~/Images/"), myfilename);
                ImageUpload.SaveAs(myfilename);
                db.Services.Add(s);
                db.SaveChanges();
             TempData["Message"] = "Registration Successful";
                TempData.Keep();
                return RedirectToAction("Index", "Homepage");
            }
            else
            {
                ViewBag.Message = "Registration Unsuccessfull....Pls try again";
                return View();
            }
            
        }



        // GET: Services/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Company_Name,Description,Type,Contact_Email,Address,Phone_no,Certification,serviceID")] Service service)
        {
            if (ModelState.IsValid)
            {
                db.Entry(service).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(service);
        }

        // GET: Services/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Service service = db.Services.Find(id);
            db.Services.Remove(service);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Vgather/Views/Services/Add.cshtml
@model Vgather.Models.Service
@{
    ViewBag.Title = "Add";
}


@using (Html.BeginForm("Add", "Services", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <link href="~/Content/career.css" rel="stylesheet" />

    <div class="form-horizontal">
        <h1 style="margin-left:800px">Join with Us</h1>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Company_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Company_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Company_Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact_Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone_no, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Certification, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Certification, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Certification, "", new { @class = "text-danger" })
                <input type="file" name="ImageUpload" required />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.serviceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.serviceID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.serviceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
                @*<input type="submit" value="Submit" class="btn btn-default" data-toggle="modal" data-target="#myModal" />*@
                <div class="container">

                    <!-- Trigger the modal with a button -->
                    @*<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Submit</button>*@

                    <!-- Modal -->
                    <div class="modal fade" id="myModal" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">

                                    <h4 class="modal-title"></h4>
                                </div>
                                <div class="modal-body">
                                    <p>Thankyou for your valuable response</p>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>

            </div>
        </div>
        @ViewBag.Message
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}