Vgather/Models/EventBooking.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vgather.Models
{
    using DHTMLX.Scheduler;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EventBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventBooking()
        {
            this.Participants = new HashSet<Participant>();
        }


        [DHXJson(Alias = "Event_ID")]
        
        public int Event_ID { get; set; }


        [Required]
        [DHXJson(Alias = "Event_Name")]
        [Display(Name = "Event Name")]
        public string Event_Name { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        public Nullable<System.DateTime> Start_Date { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "End Date")]
        public Nullable<System.DateTime> End_Date { get; set; }
        [RegularExpression("^[0-9]+$", ErrorMessage = "Invalid EventName")]
        [Display(Name = "Number of Participants")]
        public Nullable<int> No_Of_Participants { get; set; }
        public Nullable<int> Pay_Event_BookingID { get; set; }
        public Nullable<int> Venue_ID { get; set; }
        public string servicetypeid { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string EventTypeID { get; set; }
        public string Service_Company_ID { get; set; }

        [DHXJson(Alias = "Text")]
        public string Descriptions { get; set; }
        public string EventType { get; set; }
        public string Venue { get; set; }
        public string FoodCompany { get; set; }
        [Display(Name = "Equipment Company")]
        public string ElectricalCompany { get; set; }
    
        public virtual payment_Booking payment_Booking { get; set; }
        public virtual EventType EventType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual service_company service_company { get; set; }
        public virtual serviceType serviceType { get; set; }
        public virtual Venue Venue1 { get; set; }
    }
}

Vgather/Models/Payment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vgather.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.EventBookings = new HashSet<EventBooking>();
        }
    
        public string Payment_Status { get; set; }
        [CreditCard]
        [Required(ErrorMessage ="Please enter Card Number")] 
        [Display(Name = "Card Number")]
        public string CardNumber { get; set; }
        [Required(ErrorMessage = "please enter Amount")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Amount { get; set; }
        public int PaymentID { get; set; }
        public string payment_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventBooking> EventBookings { get; set; }
    }
}

Vgather/Controllers/EventBookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;

using Vgather.localhost;
using System.Web.Mvc;
using Vgather.Models;

namespace Vgather.Controllers
{
    public class EventBookingsController : Controller
    {
        private EventManagementEntities1 db = new EventManagementEntities1();

        // GET: EventBookings
        public ActionResult Index()
        {
            var eventBookings = db.EventBookings.Include(e => e.payment_Booking).Include(e => e.EventType1).Include(e => e.Payment).Include(e => e.service_company).Include(e => e.serviceType).Include(e => e.Venue1);
            return View(eventBookings.ToList());
        }

        // GET: EventBookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id != null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventBooking eventBooking = db.EventBookings.Find(id);
            if (eventBooking == null)
            {
                return HttpNotFound();
            }
            return View(eventBooking);
        }

        // GET: EventBookings/Create
        public ActionResult Create()
        {
            ViewBag.Pay_Event_BookingID = new SelectList(db.payment_Booking, "Pay_Event_BookingID", "Payment_Type");
            ViewBag.EventTypeID = new SelectList(db.EventTypes, "EventTypeID", "EventType1");
            ViewBag.PaymentID = new SelectList(db.Payments, "PaymentID", "Payment_Status");
            ViewBag.Service_Company_ID = new SelectList(db.service_company, "Service_Company_ID", "Service_Company1");
            ViewBag.servicetypeid = new SelectList(db.serviceTypes, "ServiceTypeID", "ServiceType1");
            ViewBag.Venue_ID = new SelectList(db.Venues, "Venue_ID", "Venue_Name");


            List<SelectListItem> EventName = new List<SelectListItem>();
            EventBooking Drop = new EventBooking();

            List<EventType> Event = db.EventTypes.ToList();
            Event.ForEach(x =>
            {
                EventName.Add(new SelectListItem { Text = x.EventType1, Value = x.EventTypeID.ToString() });

            });
            Drop.EventType = Convert.ToString(EventName);

            return View(Drop);
            // return View();
        }


        [HttpPost]
        public ActionResult GetVenue(string EventTypeID)
        {
            string EventID;
            List<SelectListItem> VenueName = new List<SelectListItem>();

            if (!string.IsNullOrEmpty(EventTypeID))
            {

                EventID = Convert.ToString(EventTypeID);
                List<Venue> Venues = db.Venues.Where(x => x.EventTypeID == EventID).ToList();
                Venues.ForEach(x =>
                {
                    VenueName.Add(new SelectListItem { Text = x.Venue_Name, Value = x.Venue_ID.ToString() });
                });
                Session["VenueName"] = VenueName.ToString();

            }
            return Json(VenueName, JsonRequestBehavior.AllowGet);
        }



        // POST: EventBookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Event_ID,Event_Name,Start_Date,End_Date,No_Of_Participants,Pay_Event_BookingID,Venue_ID,servicetypeid,PaymentID,EventTypeID,Service_Company_ID,Descriptions,EventType,Venue,FoodCompany,ElectricalCompany")] EventBooking eventBooking)
        {
            if (ModelState.IsValid)
            {
                db.EventBookings.Add(eventBooking);
                db.SaveChanges();
                return RedirectToAction("Summary");
            }

            Session["Event_Name"] = eventBooking.Event_Name;
            Session["Start_Date"] = eventBooking.Start_Date;
            Session["End_Date"] = eventBooking.End_Date;
            Session["No_Of_Participants"] = eventBooking.No_Of_Participants;
            Session["EventTypeID"] = eventBooking.EventTypeID;
            Session["Venue_ID"] = eventBooking.Venue_ID;
            Session["FoodCompany"] = eventBooking.FoodCompany;
            Session["ElectricalCompany"] = eventBooking.ElectricalCompany;


            ViewBag.Pay_Event_BookingID = new SelectList(db.payment_Booking, "Pay_Event_BookingID", "Payment_Type", eventBooking.Pay_Event_BookingID);
            ViewBag.EventTypeID = new SelectList(db.EventTypes, "EventTypeID", "EventType1", eventBooking.EventTypeID);
            ViewBag.PaymentID = new SelectList(db.Payments, "PaymentID", "Payment_Status", eventBooking.PaymentID);
            ViewBag.Service_Company_ID = new SelectList(db.service_company, "Service_Company_ID", "Service_Company1", eventBooking.Service_Company_ID);
            ViewBag.servicetypeid = new SelectList(db.serviceTypes, "ServiceTypeID", "ServiceType1", eventBooking.servicetypeid);
            ViewBag.Venue_ID = new SelectList(db.Venues, "Venue_ID", "Venue_Name", eventBooking.Venue_ID);
            return View(eventBooking);
        }

        // GET: EventBookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventBooking eventBooking = db.EventBookings.Find(id);
            if (eventBooking == null)
            {
                return HttpNotFound();
            }
            ViewBag.Pay_Event_BookingID = new SelectList(db.payment_Booking, "Pay_Event_BookingID", "Payment_Type", eventBooking.Pay_Event_BookingID);
            ViewBag.EventTypeID = new SelectList(db.EventTypes, "EventTypeID", "EventType1", eventBooking.EventTypeID);
            ViewBag.PaymentID = new SelectList(db.Payments, "PaymentID", "Payment_Status", eventBooking.PaymentID);
            ViewBag.Service_Company_ID = new SelectList(db.service_company, "Service_Company_ID", "Service_Company1", eventBooking.Service_Company_ID);
            ViewBag.servicetypeid = new SelectList(db.serviceTypes, "ServiceTypeID", "ServiceType1", eventBooking.servicetypeid);
            ViewBag.Venue_ID = new SelectList(db.Venues, "Venue_ID", "Venue_Name", eventBooking.Venue_ID);
            return View(eventBooking);
        }

        // POST: EventBookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Event_ID,Event_Name,Start_Date,End_Date,No_Of_Participants,Pay_Event_BookingID,Venue_ID,servicetypeid,PaymentID,EventTypeID,Service_Company_ID,Descriptions,EventType,Venue,FoodCompany,ElectricalCompany")] EventBooking eventBooking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventBooking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Pay_Event_BookingID = new SelectList(db.payment_Booking, "Pay_Event_BookingID", "Payment_Type", eventBooking.Pay_Event_BookingID);
            ViewBag.EventTypeID = new SelectList(db.EventTypes, "EventTypeID", "EventType1", eventBooking.EventTypeID);
            ViewBag.PaymentID = new SelectList(db.Payments, "PaymentID", "Payment_Status", eventBooking.PaymentID);
            ViewBag.Service_Company_ID = new SelectList(db.service_company, "Service_Company_ID", "Service_Company1", eventBooking.Service_Company_ID);
            ViewBag.servicetypeid = new SelectList(db.serviceTypes, "ServiceTypeID", "ServiceType1", eventBooking.servicetypeid);
            ViewBag.Venue_ID = new SelectList(db.Venues, "Venue_ID", "Venue_Name", eventBooking.Venue_ID);
            return View(eventBooking);
        }

        // GET: EventBookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventBooking eventBooking = db.EventBookings.Find(id);
            if (eventBooking == null)
            {
                return HttpNotFound();
            }
            return View(eventBooking);
        }

        // POST: EventBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventBooking eventBooking = db.EventBookings.Find(id);
            db.EventBookings.Remove(eventBooking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult MyAction(string button)
        {
            return RedirectToAction("Index", "Date");
        }

        public ActionResult Summary()
        {
           EventBooking eb = (from record in db.EventBookings
                              orderby record.Event_ID descending
                              select record).First();

           
            return View(eb);
        }

        [HttpGet]
        public ActionResult Payments()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Payments(Payment obj)
        {
            CreditcardValidation cchk = new CreditcardValidation();
           if(cchk.CardCheck(obj.CardNumber))
            {
                db.Payments.Add(obj);
                db.SaveChanges();
                ModelState.Clear();
                ViewBag.Success = "Payment Successful!!!!";

Vgather/Views/EventBookings/Create.cshtml
@model Vgather.Models.EventBooking

@{
    ViewBag.Title = "Book Your Event";
}

<h1><b>Event Booking</b></h1>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link href="~/Content/eventbook.css" rel="stylesheet" />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Event_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Event_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Event_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.End_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.No_Of_Participants, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.No_Of_Participants, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.No_Of_Participants, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Pay_Event_BookingID, "Pay_Event_BookingID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Pay_Event_BookingID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Pay_Event_BookingID, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Venue_ID, "Venue_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Venue_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Venue_ID, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.servicetypeid, "servicetypeid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("servicetypeid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.servicetypeid, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.PaymentID, "PaymentID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("PaymentID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PaymentID, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.EventTypeID, "EventTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("EventTypeID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.EventTypeID, "", new { @class = "text-danger" })
                </div>
            </div>*@



        <div class="form-group">
            @Html.LabelFor(model => model.EventTypeID, "EventTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EventTypeID", null, htmlAttributes: new { @id = "ddlEvent", @class = "control-label col-md-2" })
                @Html.ValidationMessageFor(model => model.EventTypeID, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.Label("VenueName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div id="Venue">
                    @Html.DropDownList("Venue_ID", null, htmlAttributes: new { @id = "ddlVenue", @name = "Venue_ID", @class = "control-label col-md-2" })


                </div>
            </div>
        </div>








        @*<div class="form-group">
                @Html.LabelFor(model => model.Service_Company_ID, "Service_Company_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Service_Company_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Service_Company_ID, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Descriptions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descriptions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descriptions, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.EventType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EventType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EventType, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Venue, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Venue, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Venue, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FoodCompany, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FoodCompany, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FoodCompany, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ElectricalCompany, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ElectricalCompany, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ElectricalCompany, "", new { @class = "text-danger" })
            </div>
        </div>



        @*@using (Html.BeginForm("MyAction", "EventBookings"))


        {
            <input type="button" value="Click to book the Venue" />

        }*@


        <button class="btn-success">@Html.ActionLink("Bookdate", "MyAction", "EventBookings")</button>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}




<script type="text/javascript">
    $(document).ready(function () {
        $('#ddlEvent').change(function () {
            $.ajax({
                type: "post",
                url: "/EventBookings/GetVenue",
                data: { EventTypeID: $('#ddlEvent').val() },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    var Venue = "<select id='ddlVenue' name = 'Venue_ID'>";
                    Venue = Venue + '<option value="">--Select--</option>';
                    for (var i = 0; i < data.length; i++) {
                        Venue = Venue + '<option value=' + data[i].Value + '>' + data[i].Text + '</option>';
                    }
                    Venue = Venue + '</select>';
                    $('#Venue').html(Venue);
                }
            });
        });


    });


</script>

Vgather/Views/EventBookings/Delete.cshtml
@model Vgather.Models.EventBooking

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventBooking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Event_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.No_Of_Participants)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.No_Of_Participants)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descriptions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descriptions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FoodCompany)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodCompany)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ElectricalCompany)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ElectricalCompany)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.payment_Booking.Payment_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.payment_Booking.Payment_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventType1.EventType1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType1.EventType1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment.Payment_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment.Payment_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service_company.Service_Company1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_company.Service_Company1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.serviceType.ServiceType1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.serviceType.ServiceType1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue1.Venue_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue1.Venue_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Vgather/Views/EventBookings/Details.cshtml
@model Vgather.Models.EventBooking

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EventBooking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Event_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Start_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Start_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.End_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.End_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.No_Of_Participants)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.No_Of_Participants)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descriptions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descriptions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FoodCompany)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodCompany)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ElectricalCompany)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ElectricalCompany)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.payment_Booking.Payment_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.payment_Booking.Payment_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventType1.EventType1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventType1.EventType1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment.Payment_Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment.Payment_Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.service_company.Service_Company1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.service_company.Service_Company1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.serviceType.ServiceType1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.serviceType.ServiceType1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue1.Venue_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue1.Venue_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Event_ID }) |
    @Html.ActionLink("EventBookings", "Payments")
</p>